### PR TITLE
Spanish language added

### PR DESCRIPTION
**Pull request by JuEnPeHa**
Created es.js
Translated to Spanish
Modified the GUI in order to show the new option (index.js and languages.js)
And next.config.js

### CODE REVIEW

**Comment by ahnafalfariza** [comment]
Hi, @JuEnPeHa thanks for making the Pull Request, sorry just replied.
I have several things to change if you don't mind. The Spanish translation (es.js) is quite different from the latest branch since we just refactored some codes and keys. Please take a look at it and adjust with the new one. Thanks

**Comment by JuEnPeHa** [comment]
> Hi, @JuEnPeHa thanks for making the Pull Request, sorry just replied. I have several things to change if you don't mind. The Spanish translation (es.js) is quite different from the latest branch since we just refactored some codes and keys. Please take a look at it and adjust with the new one. Thanks

Hey!, Thanks for the reply, I see, I will do the necessary changes tonight or tomorrow early.

Have a nice day.

**Comment by ahnafalfariza** [comment]
Thanks @JuEnPeHa , i'm looking forward to it, for note: please use develop branch since it is the latest one

**Comment by JuEnPeHa** [comment]
> Thanks @JuEnPeHa , i'm looking forward to it, for note: please use develop branch since it is the latest one

Closing this PR, I made a mistake in my side with GitHub so open a new PR in "develop" branch, thank you.

**Pull request closed without merging**
